# Generated by Django 5.2.17 on 2026-09-24 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequencia',
            options={'permissions': [('registrar_frequencia', 'Pode registrar entrada')]},
        ),
        migrations.AlterModelOptions(
            name='matricula',
            options={'permissions': [('cancelar_matricula', 'Pode cancelar matrícula')]},
        ),
    ]
