# Generated by Django 5.2.17 on 2026-09-24 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_frequencia_options_alter_matricula_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrido_em', models.DateTimeField(auto_now_add=True)),
                ('acao', models.CharField(max_length=12)),
                ('entidade', models.CharField(max_length=60)),
                ('objeto_id', models.CharField(max_length=40)),
                ('campos_alterados', models.JSONField(blank=True, default=list)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs_auditoria', to='core.unidade')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ocorrido_em', '-id'],
            },
        ),
    ]
