# Generated by Django 5.2.17 on 2026-09-24 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_logauditoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'permissions': [('ver_contato_aluno', 'Pode consultar dados de contato e nascimento do aluno')]},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'permissions': [('ver_contato_professor', 'Pode consultar contato do professor')]},
        ),
    ]
