# Generated by Django 5.2.17 on 2026-09-24 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_aluno_options_alter_professor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'permissions': [('ver_contato_aluno', 'Pode consultar dados de contato e nascimento do aluno'), ('exportar_dados_aluno', 'Pode exportar dados pessoais do aluno')]},
        ),
    ]
