# Generated by Django 5.2.17 on 2026-09-25 17:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_aluno_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateField(default=django.utils.timezone.localdate)),
                ('idade_na_avaliacao', models.PositiveSmallIntegerField()),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('altura_m', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('imc', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('classificacao', models.CharField(choices=[('abaixo_peso', 'Abaixo do peso'), ('normal', 'Peso normal ou adequado'), ('sobrepeso', 'Sobrepeso'), ('obesidade_1', 'Obesidade Grau I'), ('obesidade_2', 'Obesidade Grau II'), ('obesidade_3', 'Obesidade Grau III (Grave)')], max_length=16)),
                ('registrada_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes_fisicas', to='core.aluno')),
                ('avaliado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_avaliacao', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('peso_kg__gt', 0)), name='avaliacao_peso_positivo'), models.CheckConstraint(condition=models.Q(('altura_m__gt', 0)), name='avaliacao_altura_positiva'), models.CheckConstraint(condition=models.Q(('imc__gt', 0)), name='avaliacao_imc_positivo')],
            },
        ),
    ]
