# Generated by Django 5.2.17 on 2026-09-26 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_funcionarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='unidades_acesso',
            field=models.ManyToManyField(blank=True, related_name='gerentes_autorizados', to='core.unidade'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='abre_domingo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unidade',
            name='abre_feriado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unidade',
            name='categoria',
            field=models.CharField(choices=[('tradicional', 'Tradicional'), ('premium', 'Premium'), ('diamante', 'Diamante')], default='tradicional', max_length=12),
        ),
        migrations.AddField(
            model_name='unidade',
            name='domingo_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='domingo_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='feriado_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidade',
            name='feriado_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('nome', models.CharField(max_length=100)),
                ('abre', models.BooleanField(blank=True, default=None, null=True)),
                ('inicio', models.TimeField(blank=True, null=True)),
                ('fim', models.TimeField(blank=True, null=True)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feriados', to='core.unidade')),
            ],
            options={
                'ordering': ['data', 'id'],
                'constraints': [models.UniqueConstraint(fields=('unidade', 'data'), name='feriado_unico_por_unidade_data')],
            },
        ),
    ]
