# Generated by Django 5.2.17 on 2026-09-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_funcionario_unidades_acesso_unidade_abre_domingo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='competencia',
            field=models.DateField(blank=True, help_text='Primeiro dia do mês da mensalidade; vazio para registros anteriores.', null=True),
        ),
        migrations.AddConstraint(
            model_name='pagamento',
            constraint=models.UniqueConstraint(condition=models.Q(('competencia__isnull', False)), fields=('matricula', 'competencia'), name='uma_mensalidade_por_competencia'),
        ),
    ]
