# Generated by Django 5.2.17 on 2026-09-26 02:24

import django.db.models.deletion
from django.db import migrations, models


def preencher_acesso_historico(apps, schema_editor):
    Plano = apps.get_model('core', 'Plano')
    Matricula = apps.get_model('core', 'Matricula')
    Frequencia = apps.get_model('core', 'Frequencia')
    for plano in Plano.objects.all().iterator():
        nome = plano.nome.strip().casefold()
        categoria = {
            'premium': 'premium', 'plano premium': 'premium',
            'diamante': 'diamante', 'plano diamante': 'diamante',
        }.get(nome, 'tradicional')
        if categoria != plano.categoria:
            Plano.objects.filter(pk=plano.pk).update(categoria=categoria)
        Matricula.objects.filter(plano_id=plano.pk).update(categoria_acesso=categoria)
    for item in Frequencia.objects.filter(unidade__isnull=True).values('pk', 'matricula__aluno__unidade_id').iterator():
        Frequencia.objects.filter(pk=item['pk']).update(unidade_id=item['matricula__aluno__unidade_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pagamento_competencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='unidade',
            field=models.ForeignKey(blank=True, help_text='Unidade onde ocorreu a entrada; registros antigos recebem a unidade sede.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='core.unidade'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='acesso_tradicional_rede',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='matricula',
            name='categoria_acesso',
            field=models.CharField(choices=[('tradicional', 'Tradicional'), ('premium', 'Premium'), ('diamante', 'Diamante')], default='tradicional', editable=False, max_length=12),
        ),
        migrations.AddField(
            model_name='plano',
            name='acesso_tradicional_rede',
            field=models.BooleanField(default=False, help_text='Plano Tradicional também permite outras unidades Tradicionais.'),
        ),
        migrations.AddField(
            model_name='plano',
            name='categoria',
            field=models.CharField(choices=[('tradicional', 'Tradicional'), ('premium', 'Premium'), ('diamante', 'Diamante')], default='tradicional', max_length=12),
        ),
        migrations.RunPython(preencher_acesso_historico, migrations.RunPython.noop),
    ]
