# Generated by Django 5.2.17 on 2026-09-26 03:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_frequencia_unidade_matricula_acesso_tradicional_rede_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='matricula_anterior',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renovacao', to='core.matricula'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='valor_contratado',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
