# Generated by Django 5.2.17 on 2026-09-27 00:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_matricula_matricula_anterior_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcertoCancelamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decisao', models.CharField(choices=[('manter', 'Manter dívida ou pagamento'), ('cancelar', 'Cancelar cobrança pendente'), ('reembolsar', 'Reembolsar pagamento')], max_length=12)),
                ('valor_reembolso', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('justificativa', models.TextField()),
                ('decidido_em', models.DateTimeField(auto_now_add=True)),
                ('reembolsado_em', models.DateTimeField(blank=True, null=True)),
                ('decidido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acertos_decididos', to=settings.AUTH_USER_MODEL)),
                ('matricula', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='acerto_cancelamento', to='core.matricula')),
                ('pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.pagamento')),
                ('reembolsado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acertos_reembolsados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
