# Generated by Django 5.2.17 on 2026-09-27 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_acertocancelamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciliacaoLegado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(choices=[('associado', 'Associado ao período'), ('avulso', 'Recebimento fora do período'), ('descartado', 'Cobrança antiga descartada')], max_length=12)),
                ('justificativa', models.TextField()),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('pagamento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='conciliacao_legado', to='core.pagamento')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
