# Generated by Django 5.2.17 on 2026-09-28 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_pagamento_confirmado_por_pagamento_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='sabado_fim',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name='unidade',
            name='sabado_inicio',
            field=models.TimeField(default=datetime.time(5, 0)),
        ),
        migrations.AddField(
            model_name='unidade',
            name='semana_fim',
            field=models.TimeField(default=datetime.time(23, 0)),
        ),
        migrations.AddField(
            model_name='unidade',
            name='semana_inicio',
            field=models.TimeField(default=datetime.time(5, 0)),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='abre_feriado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='feriado_fim',
            field=models.TimeField(default=datetime.time(14, 0)),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='feriado_inicio',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
