# Generated by Django 5.2.17 on 2026-09-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_unidade_sabado_fim_unidade_sabado_inicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoRede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativa', models.BooleanField(default=False)),
            ],
        ),
    ]
