# Generated by Django 5.2.17 on 2026-09-28 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_configuracaorede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='feriado_fim',
            field=models.TimeField(blank=True, default=datetime.time(14, 0), null=True),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='feriado_inicio',
            field=models.TimeField(blank=True, default=datetime.time(8, 0), null=True),
        ),
    ]
